name: "Cloudflared SSH Tunnel - Transfer file to server"
branding:
  icon: "terminal"
  color: "orange"
description: "Lets you SCP onto a server behind a Cloudflare tunnel"
inputs:
  host:
    description: "SSH host address"
    required: true
  port:
    description: "SSH port number"
    default: "22"
  username:
    description: "SSH username"
    required: true
  private_key_filename:
    description: "SSH private key filename"
    required: true
  private_key_value:
    description: "SSH private key value"
    required: true
  service_token_id:
    description: "The Client ID of the Cloudflare service token"
    required: true
  service_token_secret:
    description: "The Client Secret of the Cloudflare service token"
    required: true
  source:
    description: "Source file"
    required: true
  target:
    description: "Target destination file"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.host }}
    - ${{ inputs.port }}
    - ${{ inputs.username }}
    - ${{ inputs.private_key_filename }}
    - ${{ inputs.private_key_value }}
    - ${{ inputs.service_token_id }}
    - ${{ inputs.service_token_secret }}
    - ${{ inputs.source }}
    - ${{ inputs.target }}

